# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gota/Documents/C++/KeroMaster

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gota/Documents/C++/KeroMaster

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/gota/Documents/C++/KeroMaster/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gota/Documents/C++/KeroMaster/CMakeFiles /home/gota/Documents/C++/KeroMaster/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gota/Documents/C++/KeroMaster/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KeroMaster

# Build rule for target.
KeroMaster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KeroMaster
.PHONY : KeroMaster

# fast build rule for target.
KeroMaster/fast:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/build
.PHONY : KeroMaster/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) -f include/CMakeFiles/imgui.dir/build.make include/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) -f _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glfw_objlib

# Build rule for target.
glfw_objlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw_objlib
.PHONY : glfw_objlib

# fast build rule for target.
glfw_objlib/fast:
	$(MAKE) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw_objlib.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw_objlib.dir/build
.PHONY : glfw_objlib/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f _deps/glad-build/CMakeFiles/glad.dir/build.make _deps/glad-build/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glad-generate-files

# Build rule for target.
glad-generate-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad-generate-files
.PHONY : glad-generate-files

# fast build rule for target.
glad-generate-files/fast:
	$(MAKE) -f _deps/glad-build/CMakeFiles/glad-generate-files.dir/build.make _deps/glad-build/CMakeFiles/glad-generate-files.dir/build
.PHONY : glad-generate-files/fast

src/ed/editor.o: src/ed/editor.cpp.o

.PHONY : src/ed/editor.o

# target to build an object file
src/ed/editor.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/ed/editor.cpp.o
.PHONY : src/ed/editor.cpp.o

src/ed/editor.i: src/ed/editor.cpp.i

.PHONY : src/ed/editor.i

# target to preprocess a source file
src/ed/editor.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/ed/editor.cpp.i
.PHONY : src/ed/editor.cpp.i

src/ed/editor.s: src/ed/editor.cpp.s

.PHONY : src/ed/editor.s

# target to generate assembly for a file
src/ed/editor.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/ed/editor.cpp.s
.PHONY : src/ed/editor.cpp.s

src/ed/entityDisplay.o: src/ed/entityDisplay.cpp.o

.PHONY : src/ed/entityDisplay.o

# target to build an object file
src/ed/entityDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/ed/entityDisplay.cpp.o
.PHONY : src/ed/entityDisplay.cpp.o

src/ed/entityDisplay.i: src/ed/entityDisplay.cpp.i

.PHONY : src/ed/entityDisplay.i

# target to preprocess a source file
src/ed/entityDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/ed/entityDisplay.cpp.i
.PHONY : src/ed/entityDisplay.cpp.i

src/ed/entityDisplay.s: src/ed/entityDisplay.cpp.s

.PHONY : src/ed/entityDisplay.s

# target to generate assembly for a file
src/ed/entityDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/ed/entityDisplay.cpp.s
.PHONY : src/ed/entityDisplay.cpp.s

src/ed/tilesetEditor.o: src/ed/tilesetEditor.cpp.o

.PHONY : src/ed/tilesetEditor.o

# target to build an object file
src/ed/tilesetEditor.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/ed/tilesetEditor.cpp.o
.PHONY : src/ed/tilesetEditor.cpp.o

src/ed/tilesetEditor.i: src/ed/tilesetEditor.cpp.i

.PHONY : src/ed/tilesetEditor.i

# target to preprocess a source file
src/ed/tilesetEditor.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/ed/tilesetEditor.cpp.i
.PHONY : src/ed/tilesetEditor.cpp.i

src/ed/tilesetEditor.s: src/ed/tilesetEditor.cpp.s

.PHONY : src/ed/tilesetEditor.s

# target to generate assembly for a file
src/ed/tilesetEditor.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/ed/tilesetEditor.cpp.s
.PHONY : src/ed/tilesetEditor.cpp.s

src/gbin/gfile.o: src/gbin/gfile.cpp.o

.PHONY : src/gbin/gfile.o

# target to build an object file
src/gbin/gfile.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/gbin/gfile.cpp.o
.PHONY : src/gbin/gfile.cpp.o

src/gbin/gfile.i: src/gbin/gfile.cpp.i

.PHONY : src/gbin/gfile.i

# target to preprocess a source file
src/gbin/gfile.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/gbin/gfile.cpp.i
.PHONY : src/gbin/gfile.cpp.i

src/gbin/gfile.s: src/gbin/gfile.cpp.s

.PHONY : src/gbin/gfile.s

# target to generate assembly for a file
src/gbin/gfile.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/gbin/gfile.cpp.s
.PHONY : src/gbin/gfile.cpp.s

src/gbin/gtypes.o: src/gbin/gtypes.cpp.o

.PHONY : src/gbin/gtypes.o

# target to build an object file
src/gbin/gtypes.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/gbin/gtypes.cpp.o
.PHONY : src/gbin/gtypes.cpp.o

src/gbin/gtypes.i: src/gbin/gtypes.cpp.i

.PHONY : src/gbin/gtypes.i

# target to preprocess a source file
src/gbin/gtypes.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/gbin/gtypes.cpp.i
.PHONY : src/gbin/gtypes.cpp.i

src/gbin/gtypes.s: src/gbin/gtypes.cpp.s

.PHONY : src/gbin/gtypes.s

# target to generate assembly for a file
src/gbin/gtypes.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/gbin/gtypes.cpp.s
.PHONY : src/gbin/gtypes.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/px/pxmap.o: src/px/pxmap.cpp.o

.PHONY : src/px/pxmap.o

# target to build an object file
src/px/pxmap.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/px/pxmap.cpp.o
.PHONY : src/px/pxmap.cpp.o

src/px/pxmap.i: src/px/pxmap.cpp.i

.PHONY : src/px/pxmap.i

# target to preprocess a source file
src/px/pxmap.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/px/pxmap.cpp.i
.PHONY : src/px/pxmap.cpp.i

src/px/pxmap.s: src/px/pxmap.cpp.s

.PHONY : src/px/pxmap.s

# target to generate assembly for a file
src/px/pxmap.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/px/pxmap.cpp.s
.PHONY : src/px/pxmap.cpp.s

src/px/str.o: src/px/str.cpp.o

.PHONY : src/px/str.o

# target to build an object file
src/px/str.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/px/str.cpp.o
.PHONY : src/px/str.cpp.o

src/px/str.i: src/px/str.cpp.i

.PHONY : src/px/str.i

# target to preprocess a source file
src/px/str.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/px/str.cpp.i
.PHONY : src/px/str.cpp.i

src/px/str.s: src/px/str.cpp.s

.PHONY : src/px/str.s

# target to generate assembly for a file
src/px/str.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/px/str.cpp.s
.PHONY : src/px/str.cpp.s

src/px/tileset.o: src/px/tileset.cpp.o

.PHONY : src/px/tileset.o

# target to build an object file
src/px/tileset.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/px/tileset.cpp.o
.PHONY : src/px/tileset.cpp.o

src/px/tileset.i: src/px/tileset.cpp.i

.PHONY : src/px/tileset.i

# target to preprocess a source file
src/px/tileset.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/px/tileset.cpp.i
.PHONY : src/px/tileset.cpp.i

src/px/tileset.s: src/px/tileset.cpp.s

.PHONY : src/px/tileset.s

# target to generate assembly for a file
src/px/tileset.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/px/tileset.cpp.s
.PHONY : src/px/tileset.cpp.s

src/rlImGui/fileBrowser.o: src/rlImGui/fileBrowser.cpp.o

.PHONY : src/rlImGui/fileBrowser.o

# target to build an object file
src/rlImGui/fileBrowser.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/fileBrowser.cpp.o
.PHONY : src/rlImGui/fileBrowser.cpp.o

src/rlImGui/fileBrowser.i: src/rlImGui/fileBrowser.cpp.i

.PHONY : src/rlImGui/fileBrowser.i

# target to preprocess a source file
src/rlImGui/fileBrowser.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/fileBrowser.cpp.i
.PHONY : src/rlImGui/fileBrowser.cpp.i

src/rlImGui/fileBrowser.s: src/rlImGui/fileBrowser.cpp.s

.PHONY : src/rlImGui/fileBrowser.s

# target to generate assembly for a file
src/rlImGui/fileBrowser.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/fileBrowser.cpp.s
.PHONY : src/rlImGui/fileBrowser.cpp.s

src/rlImGui/focusData.o: src/rlImGui/focusData.cpp.o

.PHONY : src/rlImGui/focusData.o

# target to build an object file
src/rlImGui/focusData.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/focusData.cpp.o
.PHONY : src/rlImGui/focusData.cpp.o

src/rlImGui/focusData.i: src/rlImGui/focusData.cpp.i

.PHONY : src/rlImGui/focusData.i

# target to preprocess a source file
src/rlImGui/focusData.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/focusData.cpp.i
.PHONY : src/rlImGui/focusData.cpp.i

src/rlImGui/focusData.s: src/rlImGui/focusData.cpp.s

.PHONY : src/rlImGui/focusData.s

# target to generate assembly for a file
src/rlImGui/focusData.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/focusData.cpp.s
.PHONY : src/rlImGui/focusData.cpp.s

src/rlImGui/rlImGui.o: src/rlImGui/rlImGui.cpp.o

.PHONY : src/rlImGui/rlImGui.o

# target to build an object file
src/rlImGui/rlImGui.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/rlImGui.cpp.o
.PHONY : src/rlImGui/rlImGui.cpp.o

src/rlImGui/rlImGui.i: src/rlImGui/rlImGui.cpp.i

.PHONY : src/rlImGui/rlImGui.i

# target to preprocess a source file
src/rlImGui/rlImGui.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/rlImGui.cpp.i
.PHONY : src/rlImGui/rlImGui.cpp.i

src/rlImGui/rlImGui.s: src/rlImGui/rlImGui.cpp.s

.PHONY : src/rlImGui/rlImGui.s

# target to generate assembly for a file
src/rlImGui/rlImGui.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/rlImGui.cpp.s
.PHONY : src/rlImGui/rlImGui.cpp.s

src/rlImGui/utils.o: src/rlImGui/utils.cpp.o

.PHONY : src/rlImGui/utils.o

# target to build an object file
src/rlImGui/utils.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/utils.cpp.o
.PHONY : src/rlImGui/utils.cpp.o

src/rlImGui/utils.i: src/rlImGui/utils.cpp.i

.PHONY : src/rlImGui/utils.i

# target to preprocess a source file
src/rlImGui/utils.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/utils.cpp.i
.PHONY : src/rlImGui/utils.cpp.i

src/rlImGui/utils.s: src/rlImGui/utils.cpp.s

.PHONY : src/rlImGui/utils.s

# target to generate assembly for a file
src/rlImGui/utils.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/rlImGui/utils.cpp.s
.PHONY : src/rlImGui/utils.cpp.s

src/tinyxml2/tinyxml2.o: src/tinyxml2/tinyxml2.cpp.o

.PHONY : src/tinyxml2/tinyxml2.o

# target to build an object file
src/tinyxml2/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/tinyxml2/tinyxml2.cpp.o
.PHONY : src/tinyxml2/tinyxml2.cpp.o

src/tinyxml2/tinyxml2.i: src/tinyxml2/tinyxml2.cpp.i

.PHONY : src/tinyxml2/tinyxml2.i

# target to preprocess a source file
src/tinyxml2/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/tinyxml2/tinyxml2.cpp.i
.PHONY : src/tinyxml2/tinyxml2.cpp.i

src/tinyxml2/tinyxml2.s: src/tinyxml2/tinyxml2.cpp.s

.PHONY : src/tinyxml2/tinyxml2.s

# target to generate assembly for a file
src/tinyxml2/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/KeroMaster.dir/build.make CMakeFiles/KeroMaster.dir/src/tinyxml2/tinyxml2.cpp.s
.PHONY : src/tinyxml2/tinyxml2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... package_source"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... edit_cache"
	@echo "... KeroMaster"
	@echo "... imgui"
	@echo "... raylib"
	@echo "... glfw"
	@echo "... glfw_objlib"
	@echo "... glad"
	@echo "... glad-generate-files"
	@echo "... src/ed/editor.o"
	@echo "... src/ed/editor.i"
	@echo "... src/ed/editor.s"
	@echo "... src/ed/entityDisplay.o"
	@echo "... src/ed/entityDisplay.i"
	@echo "... src/ed/entityDisplay.s"
	@echo "... src/ed/tilesetEditor.o"
	@echo "... src/ed/tilesetEditor.i"
	@echo "... src/ed/tilesetEditor.s"
	@echo "... src/gbin/gfile.o"
	@echo "... src/gbin/gfile.i"
	@echo "... src/gbin/gfile.s"
	@echo "... src/gbin/gtypes.o"
	@echo "... src/gbin/gtypes.i"
	@echo "... src/gbin/gtypes.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/px/pxmap.o"
	@echo "... src/px/pxmap.i"
	@echo "... src/px/pxmap.s"
	@echo "... src/px/str.o"
	@echo "... src/px/str.i"
	@echo "... src/px/str.s"
	@echo "... src/px/tileset.o"
	@echo "... src/px/tileset.i"
	@echo "... src/px/tileset.s"
	@echo "... src/rlImGui/fileBrowser.o"
	@echo "... src/rlImGui/fileBrowser.i"
	@echo "... src/rlImGui/fileBrowser.s"
	@echo "... src/rlImGui/focusData.o"
	@echo "... src/rlImGui/focusData.i"
	@echo "... src/rlImGui/focusData.s"
	@echo "... src/rlImGui/rlImGui.o"
	@echo "... src/rlImGui/rlImGui.i"
	@echo "... src/rlImGui/rlImGui.s"
	@echo "... src/rlImGui/utils.o"
	@echo "... src/rlImGui/utils.i"
	@echo "... src/rlImGui/utils.s"
	@echo "... src/tinyxml2/tinyxml2.o"
	@echo "... src/tinyxml2/tinyxml2.i"
	@echo "... src/tinyxml2/tinyxml2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

